{% set version = "2023.4.1" %}

package:
  name: nebari-dask
  version: {{ version }}

build:
  number: 1
  noarch: generic

requirements:
  run:
    - dask
    - distributed ==2023.4.1
    - dask-gateway ==2023.1.1

test:
  imports:
    - dask

about:
  home: https://github.com/nebari-dev
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Nebari dask dependencies."

extra:
  recipe-maintainers:
    - viniciusdc
    - iameskild
    - trallard
